[package]
name = "cube"
version = "0.1.0"
edition = "2021"

[dependencies]
bounded-integer = { version = "0.5.5", features = ["types"] }
derive_more = "0.99.17"
duplicate = "1.0.0"
itertools = "0.11.0"
tuple = "0.5.1"
